# Generated by Django 5.2.8 on 2025-11-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCardapioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JogoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cardapio.ItemCardapioImage/bytes/filename/mimetype'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cardapio.JogoImage/bytes/filename/mimetype'),
        ),
    ]
